spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/Developer/datasource/h2/spring-hello
#    username: sa
#    password:
    url: jdbc:mysql://localhost:3306/content_review?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMasterDownConnections=true
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  logging:
    level:
      root: info

  decorator:
    datasource:
      p6spy:
        enable-logging: true